CREATE TABLE PRICES (
    ID              UUID          NOT NULL,
    BRAND_ID        BIGINT        NOT NULL,
    START_DATE      TIMESTAMP     NOT NULL,
    END_DATE        TIMESTAMP     NOT NULL,
    TARIFF_ID       BIGINT        NOT NULL,
    PRODUCT_ID      BIGINT        NOT NULL,
    PRIORITY        INTEGER       NOT NULL,
    PRICE           DECIMAL(10,2) NOT NULL,
    CURRENCY_CODE   CHAR(3)       NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_PRICES PRIMARY KEY (ID)
);